name: .NET Build & Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build src/Chirp.CLI/ --configuration Release

      - name: dotnet publish
        run: dotnet publish src/Chirp.Webservice/ -c Release -o ${{env.DOTNET_ROOT}}/myapp
