name: Project-Automation

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/ITU-BDSA2025-GROUP25/projects/2
          github-token: ${{ github.token }}
